### ISSUE TITLE
The good old C error

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#103]
Found an easy one today:
```python
for i in range(101):
    if i % 2 = 0:
        print(i)
```

which currently gives:

## Python exception

```pytb
    Traceback (most recent call last):
      File "solution.py", line 2
        if i % 2 = 0:
                 ^
    SyntaxError: invalid syntax
```

A `SyntaxError` occurs when Python cannot understand your code.

Python could not understand the code in the file
'solution.py'
beyond the location indicated below by --> and ^.

```
       1: for i in range(101):
    -->2:     if i % 2 = 0:
                       ^
```

### Python's error message (invalid syntax) cannot be used to identify the problem

Currently, I cannot guess the likely cause of this error.
Try to examine closely the line indicated as well as the line
immediately above to see if you can identify some misspelled
word, or missing symbols, like (, ), [, ], :, etc.

You might want to report this case to
https://github.com/aroberge/friendly-traceback/issues

**Comment by aroberge** [comment]
Yes, indeed, this is something that definitely needs to be identified. I'll get to work on it right away.

**Comment by aroberge** [comment]
Fixed for `if` case as well as `elif`.  I also added support for `while`; I cannot think of any other similar case.

New version uploaded to Pypi.org.

**Comment by alexmojaki** [comment]
What about `do_thing(is_bar=foo()="bar")`? Why limit it to expressions directly in conditional statements? Perhaps once you find the offending token you could try replacing it with `==` and see if the program is now valid syntax?

**Comment by aroberge** [comment]
@alexmojaki This is a good point. At the moment, I never proceed to reevaluate if a program has a valid syntax. To be honest, I never thought of doing it ... and have already a function (`editors_helper.check_syntax`, https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/editors_helper.py#L20) that could be used for that purpose.

**Comment by aroberge** [comment]
I might have to revisit the current message: it could be that instead of a normal assignment, what is required is using the walrus operator: this is certainly the case in `while` statements and possibly in other contexts.
