### ISSUE TITLE
Malformed variable names

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#108]
Just some thoughts about potential syntax errors which seem unhandled. I don't know if these are actually common mistakes.

- Name containing a space, e.g. `my name = "Alex"`
- Name containing a dash, e.g. `my-name = "Alex"`. There is a special message for this but maybe it could suggest underscores instead of `-`.
- Name starting with a number, e.g. `2x = 3` or `2pi * r`. In the former case one would point out that this is just an invalid name, in the latter one might suggest `2 * pi`.

**Comment by aroberge** [comment]
Issue noted as well as the other one. I do not know if you get notices when a label is applied.

**Comment by alexmojaki** [comment]
> I do not know if you get notices when a label is applied.

I don't, but it's fine.

**Comment by aroberge** [comment]
Moved to #110
