### ISSUE TITLE
Moving docs to separate repository

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#11]
When adding or modifying test cases or translations, I almost always run some scripts to update the documentation and visually inspect the changes. This works well in terms of quality assurance but tends to clutter commits and make inspection of changes using tools such as gitk or Sublime Merge more tedious than it should be.

I have thus decided to more the documentation to a separate repository (visible at https://aroberge.github.io/friendly-traceback-docs/docs/html/). 

However, updating the documentation using the scripts included in this repository assumes that both this repository and the documentation directory are found at the same level on a local computer, with hard-coded names:

````
    base_path/
            +- friendly-traceback/
            +- friendly-traceback-docs/
```

**Comment by stuaxo** [comment]
The text on Pypi probably needs updating as it still links to this tickets

https://pypi.org/project/friendly-traceback/

**Comment by aroberge** [comment]
Thank you @stuaxo for reporting this.
