### ISSUE TITLE
Level, verbosity, and include

### ISSUE THREAD

**Issue by alexmojaki** [aroberge/friendly-traceback#114]
- `install()` has a default `include="minimal"`, while everything else seems to have `include="explain"` as the default. This threw me way off for a while.
- The documentation https://aroberge.github.io/friendly-traceback-docs/docs/html/usage_adv.html talks about verbosity functions which don't exist, not `include`.
- `set_level()` says in its docstring "Deprecated; use set_verbosity() instead". `set_verbosity` doesn't exist. It prints "friendly-traceback set_level is deprecated; defaults will be used." but the printed message also doesn't explain what to do instead.

**Comment by aroberge** [comment]
Yes, the documentation is hopelessly behind ... and I do need to change the default for `install()`.  When I used numerical `verbosity` levels, the default was to show everything (corresponding to `include="explain"`).  Since this resulting in too much information potentially overwhelming the users, I changed the defautl in most places to show only the minimal amount of useful information.

However, in doing so and as you found out, I "broke" the default to be used for install().  This is definitely a bug. I'll try to find the time to change it within the next couple of hours and push a new version to Pypi.

**Comment by aroberge** [comment]
I used to provide more than 11 or 12 different ways to use friendly-traceback.  I am in the process of reducing this to a more sensible number, and try to ensure that the relevant amount of information is shown by default in each case.  Previously, the verbosity level was an integer ... which was not very helpful in trying to figure out what value should be used in what context.

Currently, the scenarios I have in mind are the following:

1. Run a script:  `python -m friendly_traceback script.py`. In this case, we want to have all the information shown as the user may not have the possibility of running the file again before fixing the cause of the exception.  Default value: `include = "explain"`.

2. Run a script, but drop in interactive mode at the end (-i Python flag):  `python -im friendly_traceback script.py`. In this case, the user will have the opportunity to find more information from the REPL (using `why(), where(), what(), explain(), ...`) if needed. So, we only show a minimal amount of info by default (the traceback and the `hint()`).  Default value: `include = "minimal"`.

3. Start the friendly interactive console: `python -m friendly_traceback`.  Same default as 2 above.

4. Using `install()`. Here we cannot assume that the user will be able to ask for more information after an exception is raised. As you found before, the default value was incorrect in this case.

5. Using it locally in a program:

```python
import friendly_traceback
try:
   something
except SomeException:
   friendly_traceback.explain()
```
Here, the default is `include = "explain"`.  Currently, one cannot change this default using a keyword argument for `explain()`, which I should fix.  I do use this for unit tests, as well as in the friendly-console ... but I don't think that it is likely to be used by other people.

6. Running a program from an editor (say IDLE, Mu, VS Code, etc.)  Here one can write a short helper file containing the following:
```python
from friendly_traceback import run

result = run("error.py")
```
By default, `run` will start a "friendly console" allowing one to get more information if needed. The default arguments for `run()` are
```python
def run(
    filename,
    lang=None,
    include="minimal",
    args=None,
    console=True,
    use_rich=False,
    theme="dark",
)
```
where `args` are the arguments that one would pass to a program on command line.

I **think** that this covers all the relevant scenarios. I definitely do need to update the documentation.

**Comment by alexmojaki** [comment]
All of these scenarios assume that the user wants friendly-traceback to do the formatting. Remember the API for just getting the info. I suppose that's what `get_traceback_info` is for, but personally I don't use it in futurecoder because:

1. I don't want to waste CPU time and possibly get irrelevant errors for things that I'm not going to use, and
2. I don't want it to print things like `WARNING: Internal error caught in get_likely_cause()` when there's an exception.

So instead I call `get_generic_explanation`, `get_likely_cause`, and `set_cause_syntax` myself directly and handle exceptions suitably. But this is shaky because then `info` needs to contain some things which would usually be populated by `get_traceback_info`, and those things change over time.

**Comment by aroberge** [comment]
You can set your own formatter; this is done, for example, by https://www.hackinscience.org/.   

(See https://github.com/JulienPalard/correction-helper)

And, as much as I **love** having people testing and using Friendly-traceback, as stated on https://aroberge.github.io/friendly-traceback-docs/docs/html/:
**This is alpha software, currently in development. The API is subject to change without notice.**

Because friendly-traceback is used in a public site with many users, I do try to make sure that the keys in the `dict` passed to custom formatters do not change meaning. I have added one dict item (corresponding to the "hint") in the recent past, but did not change any of the existing ones.

Regarding the `WARNING: Internal error ...`, these definitely signal that there are bugs.  I do need to see such messages to find these bugs, and fix the code.

**Comment by alexmojaki** [comment]
> You can set your own formatter; this is done, for example, by https://www.hackinscience.org/.

Thank you, that looks like a very interesting project with lots of similarity to futurecoder. I will definitely be looking into it for inspiration and more. correction-helper in particular sounds like something I'd want to use in futurecoder.

However, setting a custom formatter solves neither of the problems mentioned.

> This is alpha software, currently in development. The API is subject to change without notice.

I completely understand that, and I'm not saying you should avoid changing the API. I will soon do the opposite. The problem is that the API changes in subtle ways that are difficult to detect. For example recent changes mean that `get_likely_cause` now needs `bad_line` in the `info` dict. This isn't an obvious change like a new function argument which needs to be passed. It's just one of many string keys of an untyped dict. The dict gets mutated in many places deep in function calls. The key is only needed sometimes so it's easy to not realise you need it.

> Regarding the WARNING: Internal error ..., these definitely signal that there are bugs. I do need to see such messages to find these bugs, and fix the code.

The messages definitely need to appear somewhere. But I think they are being produced at the wrong layer. `get_traceback_info` is about getting info, not displaying it. Either the formatter or some other high level component concerned with output would be better suited. By contrast, optionally raising exceptions based on a debug flag is good and should probably stay in `get_traceback_info`.

This is a great library full of very useful gems. You've put a lot of work into detecting many different error cases and it shows. I just want it to be easier to access this functionality for me and others like me who are using it to build higher level tools, and that includes hackinscience. I think there needs to be a little less focus on people using friendly traceback directly, e.g. with the console, and are happy to let it make all the decisions.

For example, in my case I only want the generic message and likely cause. Suppose I use `get_traceback_info`, find some way to deal with the printed messages, and don't worry about the performance cost. There's still a lot of code that isn't wrapped in any exception handling. If, say, `format_python_tracebacks` fails with an exception, then the entire function fails. I can catch the exception but I have no way of getting the information I wanted. I don't need `format_python_tracebacks` so this would be very frustrating. Since this is alpha software I need to treat this as a likely possibility and only call the lower level functions I need.

If I may, I'd like to suggest an approach that has worked extremely well for me in a very similar situation and that I think would work well here too. The [`stack_data.FrameInfo` class](https://github.com/alexmojaki/stack_data/blob/master/stack_data/core.py#L456) is pretty analogous to the `info` dict in friendly traceback. It's the main place where all the interesting raw data lives. It's very easy to use from the outside: you just initialise it with a frame or traceback object and any configuration options you're interested in, and then access whatever you want *as an attribute*. You don't need to do any other preparation or pass arguments to any methods. It has zero instance methods with parameters. But most of the attributes are not set upon initialisation, they're cached properties. Overall this has many benefits:

- It's easy to get only the properties you need without computing anything unnecessary. It's all lazy, on demand, and cached.
- It's obvious from scrolling through the class which properties exist. This is also documented but maintaining documentation is hard.
- Each property is nicely type hinted.
- The body of each property clearly declares which other properties it depends on. Just look for `self.`
- Navigating around the class is very easy. Especially in my IDE, it's infinitely easier to click on a property access and jump to its definition than it is to search for code like `info["bad_line"] = ` and all its possible variants.
- In friendly-traceback, it would make it easier and safer to change the API as the library develops as the impact of changes would be more obvious and more isolated.

I understand that this level of refactoring seems daunting. I think it would actually turn out to be quite straightforward, but that may not be much comfort. Please just take some time to ruminate on the benefits and consider. You may not follow exactly the suggested format but hopefully you can be inspired to come up with a similar method that suits your needs better. In the end such a refactoring would probably make the codebase as a whole easier for you to develop and maintain. Eventually, if the library stops being alpha and the API needs to stabilise, such a change will be much harder if not impossible.

**Comment by aroberge** [comment]
Thanks for this thoughtful feedback. I will read it again (and again) and think about it.  From my first read through, what you wrote makes a lot of sense.

 Just ~~one ~~ two quick comments.

1. You are reaching deep in the bowels of my code. My plan, is to keep all the public API in two files; the first named ... public_api.py (https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/public_api.py), and the other being the console.  In the docstring of the public_api file, I wrote

```python
"""
If your code requires access to functions or classes that are not
made available here and are not part of Friendly-console, please
file an issue.
"""
```
I don't think I am ready yet to make many more functions available, as I have been doing a lot of refactoring of many internal functions, adding new keyword arguments being passed around, etc.  This, especially if I change the code along the lines you suggest.

However, you really got me even more curious about what you do and I will definitely have to get a good look.

2. I plan to make at least one more addition to the information being available, dealing with `SyntaxWarning` and other warnings.

**Comment by alexmojaki** [comment]
> Thanks for this thoughtful feedback. I will read it again (and again) and think about it. From my first read through, what you wrote makes a lot of sense.

Hooray!

> 1. You are reaching deep in the bowels of my code.

Indeed, it's really not ideal.

> My plan, is to keep all the public API in two files; the first named ... public_api.py (https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/public_api.py)... I don't think I am ready yet to make many more functions available

If `info` was a class as suggested, then the entrypoint for users could still be `set_formatter`. They would just be able to use attribute access instead of dict access (you could even make both possible for compatibility). The `info` dict isn't a function in `public_api.py` but its structure is still part of the public API. Right now I can't see where that API is documented, if at all. With a class, each property could have its own easily discoverable docstring.

> ```python
> """
> If your code requires access to functions or classes that are not
> made available here and are not part of Friendly-console, please
> file an issue.
> """
> ```

Ah, I don't think I saw that. I probably would have filed an issue. I could see that I was reaching deeper than intended but I didn't think it was a problem at first.

> I plan to make at least one more addition to the information being available, dealing with `SyntaxWarning` and other warnings.

I'm not quite sure what you mean, but in general adding keys to `info` is not a problem. The problem is when those keys become required.

**Comment by aroberge** [comment]
>
> If info was a class as suggested, then the entrypoint for users could
> still be set_formatter. They would just be able to use attribute access
> instead of dict access (you could even make both possible for
> compatibility).
>

I have been thinking about this very idea (being able to access it both as
though it was still a dict and using attribute access) but don't know (yet)
how to do this.  Are you familiar with any such example?   I have some
vague recollections that pyglet did this years ago, but have never seen
anyone else do this.

**Comment by alexmojaki** [comment]
Off the top of my head:

```python
class Subscriptable:
    def __getitem__(self, item):
        try:
            return getattr(self, item)
        except AttributeError as e:
            raise KeyError from e
```

Your info class can mixin that, as well as any other classes that were previously inner dicts within `info`.

**Comment by aroberge** [comment]
Ok, not quite what you had in mind, but I've made a first tiny step towards making some information available without having to compute everything.

```
>>> from friendly_traceback import get_what
>>> print(get_what('ImportError'))
An `ImportError` exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.

>>> print(get_what('NameError', lang='fr'))
Une exception `NameError` indique que le nom d'une variable
ou d'une fonction n'est pas connue par Python.
Habituellement, ceci indique une simple faute d'orthographe.
Cependant, cela peut également indiquer que le nom a été
utilisé avant qu'on ne lui ait associé une valeur.
```

In the traceback info, this is currently available as `info["generic"]`. I also refer to it in the documentation, as the "generic" explanation about a given exception.  So, it would seem to make sense to call this function `get_generic()` instead of `get_what()`

However, since I had made this information available in the friendly_console (after an exception was raised) with the command `what()`  [part of the series `what(), why(), where(), explain(), more(), ...`], I thought it might make sense to use `get_what()`, instead of `get_generic()`.

While I understand the idea of defining a special class, with documented attributes like you described (and I almost certainly will do this), I'm thinking that it possibly make more sense to define simple functions like `get_what()` as part of the public API, and have them require the smallest amount of information possible (and least amount of internal computation) to return a result. 

Does this approach make sense to you?

**Comment by alexmojaki** [comment]
I think this makes sense for simple things like `get_what` which don't depend on much else. For more complicated things like the likely cause, if the implementation is more complicated than `return get_traceback_info()["cause"]` then it's probably going to be more work than the class approach.

**Comment by aroberge** [comment]
@alexmojaki In the developement version, internal warnings are no longer automatically printed. I have added them as an additional traceback item `info["WARNING"]`. If you use your own formatter to select which arguments to show, you will now be able to exclude them.  They are printed when using the default formatters.

This will be documented when I implement the class-based version of what is currently in the `info` dict.

If you need it, I can upload a new version that to Pypi.

**Comment by alexmojaki** [comment]
Cool, that sounds like a step in the right direction. No need to upload to PyPI, I will use github if needed.

**Comment by aroberge** [comment]
Documentation has been updated as a preliminary step to introducing a class instance instead of a dict for traceback information. `info["WARNING"]` has been replaced by `info["debug_warning']`.
