### ISSUE TITLE
Create a FriendlyTraceback class

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#117]
This issue arises from the discussion on #114.  

Instead of using the `info` dict to contain all the information created by friendly-traceback "all at once" when an exception is raised, a custom class, tentatively named `FriendlyTraceback`, should be used, with its attributes corresponding to the current items in the `info` dict.  Thus, we might have:

```python
class FriendlyTraceback:
   def __init__(self, exception_type, value, tb, lang='en'):
        self.parsing_error_source = None  # corresponding to info["parsing_error_source"]
        ...
```
For convenience of formatters, instance attributes should also be accessible as keys in a dict, like they are currently.

The information should be computed "on demand". Thus, if someone only wants to use part of the information available from friendly-traceback, it should be possible to do so without having friendly-traceback do the work to initialize all possible attributes.

Possible attributes that could be made available to a custom formatter should be documented in docstrings, with this class information be automatically added to the online documentation.

With the current design, if one wants to change the language in which the explanations are provided, the user must explicitly set the language and then raise the exception again.  One goal of the new design should be to be able to recreate the friendly-traceback information in a different language without having to raise the exception again, but simply by re-using some relevant stored by the class instance. However, because of the way that gettext works, we would still have to redo some, or all of the introspection done by friendly-traceback based on the objects that are passed to it, before showing the information in a different target language.

Unlike almost all the development done on this project, this work should probably be done in a separate branch.

Other than opening some new possibilities for third-party users, this work should result in very little change in what is already available to the end users. What **is** currently available is poorly documented.  Before this work begins, the existing documentation should be updated. Documenting and reflecting upon the public API (what it is, and what it should be) would likely be something useful to do before tackling this issue.

**Comment by aroberge** [comment]
Add a `set_context(total=5, before=3, after=1)` function/method to set how many lines in total, before, and after the line identified as having an error are going to be shown. When this function is called, update the information if it exists, or use it as the new default.

**Comment by alexmojaki** [comment]
I'd be wary of a method like `set_context` which would mean either having cache invalidation or no cache at all.

**Comment by aroberge** [comment]
There are two types of projects that will use Friendly-traceback: some like yours and HackInScience, which get the information once, and those where a user interacts with a console. In the first case, perhaps people running these projects will not like the default values I currently use; with this function/method, they will be able to choose their own default values.  For people using the console (say, beginners learning programming with IDLE), being given the flexibility to change default values after a traceback has been shown and have it displayed again would likely be useful.

**Comment by aroberge** [comment]
Inspired by https://jslvtr.com/posts/better-python-console-apps-with-rich, use this opportunity to use Rich directly in the new class rather than through a formatter that has tacked on `if` statements to deal with special formatting.

**Comment by aroberge** [comment]
As it turned out, various tools I am using for documenting, including automatically comparing differences between Python versions and recording changes, depended on having the information available as a dict with no extra keys. In the end, I ended up recreating a dict as an attribute of a class.  As I am recording this, the new method reproduces all the results of the old approach. However, all relevant attributes (dict items) are clearly set inside the class (currently called `FriendlyTraceback`), which should make it easier for anyone wishing to use only parts of this code.

The new code is only partially documented. I need to complete the docstrings, rename a few attributes as well as another class (currently named `RawInfo`) and remove some dead code, after which I need to ensure that all the ways of using friendly-traceback mentioned in the documention work as advertised.

Once this is done, I will close this issue and try to tackle all remaining issues before looking at making use of `Executing`.

**Comment by aroberge** [comment]
I did not implement some of the additional ideas I mentioned in a couple of comments but the main goal has been accomplished. Closing this issue to focus on other ones.
