### ISSUE TITLE
Add support for IPython

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#126]
After the backlog issue is taken care of, I should look at seeing how to integrate with IPython.

**Comment by Carreau** [comment]
Great ! Thanks; if you ever get to it I would be ok to have friendly TB be automatically enabled in IPython if installed.

**Comment by aroberge** [comment]
@Carreau I just released a new version (0.2.0) of Friendly-traceback with experimental support for IPython. It's not ideal, but it is a first step.  I took three screenshots to illustrate the project status.

First, an example using Friendly-traceback's own console, running on Windows with the new Windows terminal and using Rich (https://github.com/willmcgugan/rich)

![image](https://user-images.githubusercontent.com/629698/101661988-5175bd80-3a1f-11eb-8d9c-3a7e6a687688.png)

Above, I used `where()` to show additional information after the traceback; other commands are available. I just added a subset of what is found on https://aroberge.github.io/friendly-traceback-docs/docs/html/repl.html

Next, showing how to enable Friendly-traceback within IPython, running the exact same example as above, but without any syntax colouring.

![image](https://user-images.githubusercontent.com/629698/101662124-79652100-3a1f-11eb-8977-861c3a7c154a.png)

Finally, using Rich to provide colours, I display the same result as before.

![image](https://user-images.githubusercontent.com/629698/101662179-913ca500-3a1f-11eb-8e18-d2392370bd07.png)

The result is clearly not satisfying. I'm using my own styles instead of Rich's default which might be why this happens.

So, it is ready for experimentation, but more work is needed before it could be considered for serious work.

= = =
Unrelated: I see IPython is using a rather "unfriendly" scheme for caching results of computation in an attempt at doing preventing duplicates.  I was wondering if something much simpler could not be used instead.  I would suggest to use a global counter ("kernel count") which would be a simple integer that could be incremented by 1 each time a new `CachingCompiler` instance is intantiated.  This would allow unique names of the form
`<ipython-input-cell-kernel>`.   Of course, I might be missing something obvious which might prevent this from working ...

**Comment by aroberge** [comment]
I just noticed that `SyntaxError`s are not captured. So, there is definitely more work to be done - in addition to getting the syntax colouring to work properly.

**Comment by aroberge** [comment]
`SyntaxError` support added.
![image](https://user-images.githubusercontent.com/629698/101668891-838b1d80-3a27-11eb-991a-41ccfd36f9a4.png)

**Comment by alexmojaki** [comment]
Take note of the overlap:

1. IPython uses `stack_data` by default in master
2. friendly-traceback may use stack_data (#96)
3. @willmcgugan has said he plans on using some of the libraries, including perhaps stack_data. I suggested it in https://github.com/willmcgugan/rich/issues/145 which is now closed but based on the last comment and https://www.reddit.com/r/Python/comments/jxsiyn/even_more_prettierer_tracebacks/gcyqr27/?context=3 it seems to still be in the cards.

**Comment by aroberge** [comment]
I know that IPython uses stack_data. 

I spent a few hours trying to use it as a replacement for the formatter I wrote, as I like how it works with "pieces" instead of lines. However, I could not get it to work reliably both in the console and when running an external file; it was also giving some problems when dealing with SyntaxErrors.  

One problem I have is that I remove from the stack frames that belong to friendly_traceback modules and some Python modules. I also do this now for embedding with IPython; other users (such as hackinscience) do that as well.

**Comment by Carreau** [comment]
> Unrelated: I see IPython is using a rather "unfriendly" scheme for caching results of computation in an attempt at doing preventing duplicates. I was wondering if something much simpler could not be used instead. I would suggest to use a global counter ("kernel count") which would be a simple integer that could be incremented by 1 each time a new `CachingCompiler` instance is intantiated. This would allow unique names of the form
> `<ipython-input-cell-kernel>`. Of course, I might be missing something obvious which might prevent this from working ...

This logic may predate me joining the project, so I would have to dig into it to figure this out; 
The traceback features of IPython are among the oldest ones (from before bool were introduced in Python), so I'm fine trying new things. 

I'd also love to have a way to render traceback to HTML without having to go through the ansi escape code.

**Comment by aroberge** [comment]
Experimental support for JupyterLab; using Pygments to write html, and using `from IPython.display import display, HTML` to show the tracebacks.
![image](https://user-images.githubusercontent.com/629698/101709367-b48a4300-3a65-11eb-9132-eca973f353d8.png)

**Comment by aroberge** [comment]
After doing some relatively minor changes, I've added a section to the documentation about using Friendly-traceback with IPython, either in console environments or in notebook environments. The documentation can be found here: https://aroberge.github.io/friendly-traceback-docs/docs/html/ipython.html

Closing this issue as I consider the original goal accomplished.
