### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by dcambie** [aroberge/friendly-traceback#148]
```
if 1 in "123":
    print()
```
Clearly left operand has to be a string in this case.

This triggers the "I do not recognize this case." message in friendly-traceback
[relevant Stack-overflow question](https://stackoverflow.com/questions/24831961/typeerror-in-string-requires-string-as-left-operand-not-int)

Being a TypeError is not part of the contest ;)

**Comment by aroberge** [comment]
On Tue, Jan 19, 2021 at 5:55 PM dcambie <notifications@github.com> wrote:

> if 1 in "123":
>     print()
>
> Clearly left operand has to be a string in this case.
>
> This triggers the "I do not recognize this case." message in
> friendly-traceback
> relevant Stack-overflow question
> <https://stackoverflow.com/questions/24831961/typeerror-in-string-requires-string-as-left-operand-not-int>
>
> Being a TypeError is not part of the contest ;)
>

Still, this will be useful for the next version. Thanks.

**Comment by aroberge** [comment]
Actually, since you provided a link to a StackOverflow question, I will consider it as a valid entry for the contest.

**Comment by aroberge** [comment]
Closing: added to TypeError cases.
