### ISSUE TITLE
SyntaxError: invalid syntax if an invalid variable name is used with a walrus operator (works with normal assignments)

### ISSUE THREAD

**Issue by dcambie** [aroberge/friendly-traceback#149]
```python
import time

if var start := time.time() < end_of_time:
    pass
```

Gives a "SyntaxError: invalid syntax" where friendly-traceback says: "Currently, I cannot guess the likely cause of this error."

This should probably generate a message similar to

```python
import time
var start = time.time()
```
which incidentally has (imho) a minor typo in the description, i.e. it says "Python indicates that the error is caused by var written immediately after start." with the two word "var" and "start" swapped, it is start that is immediately after var!

**Comment by aroberge** [comment]
Thanks. I'm away from my computer now. I'll give a proper response later,
but this look like a valid case to consider!

**Comment by aroberge** [comment]
Thanks both for this new case, which I will have to figure out how to recognize automatically, and for the "typo".

**Comment by aroberge** [comment]
Typo fixed in repo.
![image](https://user-images.githubusercontent.com/629698/105112887-3d9b8d80-5a9a-11eb-85e0-b7f1e7edb331.png)

**Comment by aroberge** [comment]
Contest entry fixed in repo.
![image](https://user-images.githubusercontent.com/629698/105352012-b77b6600-5bc3-11eb-9286-22f2bff3c8ce.png)

**Comment by aroberge** [comment]
Test case added.
