### ISSUE TITLE
Contest: 

### ISSUE THREAD

**Issue by sdementen** [aroberge/friendly-traceback#152]
the following syntax error could be better explained...
```
def foo(a, **kwargs, b, *args, c):
    print("hello")
```
```

┌─────────────────────────────── Python exception ───────────────────────────────┐
│ Traceback (most recent call last):                                             │
│   File "test.py", line 1                                                       │
│     def foo(a, **kwargs, b, *args, c):                                         │
│                          ^                                                     │
│ SyntaxError: invalid syntax                                                    │
│                                                                                │
│ A SyntaxError occurs when Python cannot understand your code.                  │
│                                                                                │
│ Python could not understand the code in the file 'test.py' beyond the location │
│ indicated by --> and ^.                                                        │
│                                                                                │
│     -->1: def foo(a, **kwargs, b, *args, c):                                   │
│                                ^                                               │
│                                                                                │
│ The opening parenthesis ( on line 1 is not closed.                             │
│                                                                                │
│ 1: def foo(a, **kwargs, b, *args, c):                                          │
│           |                                                                    │
└────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by aroberge** [comment]
I completely agree: the error is definitely not due to an unclosed bracket.

**Comment by sdementen** [comment]
There are some variants of the syntax error that also generate the same explanation

**Comment by aroberge** [comment]
Yes, I can see that; however, I would consider them to be effectively the same issue.  (sorry about that.)

**Comment by aroberge** [comment]
Sorry, I should have been more explicit: I see the root cause as a wrong order of `*arg`, `**kwargs` and other args.  To give the proper explanation, Friendly-traceback must be able to analyze the order of such args, and suggest the correct ordering, no matter what permutation or arguments is used in the user-written code.  Note that this, to my mind, includes duplicate use of `*args`, etc.

If you find a mistake that is not a permutation (or similar) of what you have submitted, then it could possibly be considered as a second contest entry.

**Comment by sdementen** [comment]
these two cases get the same explanation today but tomorrow could get different explanations
```python
# possible explanation: argument of a function should be valid python variable names
def foo(a, =, b):
    print("hello")

# possible explanation: argument of a function should be valid python variable names (/ is only supported as of pyhton 3.8)
def foo(a, /, b):
    print("hello")
```

**Comment by aroberge** [comment]
I agree that these belong to different case classes than the first one you submitted. So, I count this as two additional valid entries.

**Comment by aroberge** [comment]
BTW, valid entries are also recorded in issue #145 so that I can keep track of the proper count.

**Comment by sdementen** [comment]
with python 2 code that is not valid anymore in python 3 (unpacking in function signature)
```python
# possible explanation: lambda does not require parentheses around the arguments. If you wanted to unpack the *first* argument, this is not possible anymore in python 3.
lambda (a,b): a
```

```python
# possible explanation: you cannot unpack an argument in the function, assign it to a parameter and unpack it within the body of the function.
lambda c, (a,b): a
```

**Comment by aroberge** [comment]
I definitely have not considered tuple unpacking in function arguments.  It is at least one additional valid entry. I'll have to think about whether or not the two examples you gave correspond to a different class of errors.

**Comment by aroberge** [comment]
After thinking some more about it, I'm inclined to consider the two unpacking examples as separate entries since they would likely warrant two different explanations, like you suggested.

**Comment by aroberge** [comment]
Possibly relevant examples from StackOverflow: https://stackoverflow.com/questions/21892989/what-is-the-good-python3-equivalent-for-auto-tuple-unpacking-in-lambda#21893219

**Comment by sdementen** [comment]
the simplest/shortest one ?
```a=
```
│ Currently, I cannot guess the likely cause of this error. Try to examine       │
│ closely the line indicated as well as the line immediately above to see if you │
│ can identify some misspelled word, or missing symbols, like (, ), [, ], :,     │
│ etc.                                                                           │
│                                                                                │
│ Unless your code uses type annotations, which are beyond our scope, you might  │
│ want to report this case to                                                    │
│ https://github.com/aroberge/friendly-traceback/issues                          │
└────────────────────────────────────────────────────────────────────────────────┘

(btw, no worry about the contest, I am not trying to flood the system to win it. It is just input for your project to make it even better)

**Comment by aroberge** [comment]
Ah ... a single question mark.  Taken as per your comment: to improve friendly-traceback ... but not really fitting the goal as I cannot really consider this valid code at all. Still, I'll have to take care of something like this.

**Comment by sdementen** [comment]
sorry, I corrected my post as it was showing no code at all

**Comment by aroberge** [comment]
Better example ... but I don't think I can count it as a valid submission, given the goals of Friendly-traceback. I cannot see anyone needing help with this type of error. Still, I should probably try to see if I can make the analysis more robust so as to handle this case...

**Comment by sdementen** [comment]
I agree. Maybe better for these kind of errors to not have the message about reporting them to you. But it maybe tricky as you could miss interesting cases

**Comment by sdementen** [comment]
some bug I am sometimes facing (even after +17y of python) is the following
```python
a="hello", # in real a way more complex expression like a list comprehension or a multi-line expression but ending with an extra trailing comma that should not be here

# long below the code above (or in another function), I try to access the object a but fail as I am in fact having a tuple of length one with my object as it first and unique element
print(a.upper())
```
==>
```
The object a has no attribute named upper. The following are some of its known attributes: count, index.
```
this is too simplified but obviously, the trailing comma should be removed (I get this kind of pattern when I refactor the code and some trailing comma is hidden at the end of a more complex expression).

It could be detected if:
- the object with attribute error is a tuple of size 1 (already weird/rare configuration as tuples are immutable and there to be able to group more than 1 object)
- the first object of the tuple has an attribute with the right name

So for the example above, an alternative message like
```
The object a has no attribute named upper. But object a is a tuple with a single element which has an attribute named upper.
Check if there is not a spurious trailing comma at the end of the definition of the object a.
```

**Comment by aroberge** [comment]
[example about tuple of length 1]
This is an interesting/intriguing example and your suggestion about how to analyze it fits in very well with my general approach. I don't think it would be very frequent but it is the type of example that I really like to work on (unlike the `SyntaxError: invalid syntax` cases).

**Comment by aroberge** [comment]
BTW, unrelated to the contest, since you've obviously played with Friendly-traceback quite a bit, I was wondering if you had any suggestions/constructive criticism to offer regarding ways to improve it - including its documentation, assuming you've looked at it.

**Comment by sdementen** [comment]
another one I am bitten sometimes myself

```python
def foo(a,b):
    pass

# there is a missing trailing comma between the two lists
foo([1,2,3]
    [3,4,5])
```
yet the error explanation is
```
A TypeError is usually caused by trying to combine two incompatible types of objects, by calling a function with   
the wrong type of object, or by trying to do an operation not allowed on a given type of object.                  
                                                                                                                   
In the expression [1,2,3]    [3,4,5] what is included between the square brackets, [...], must be either an        
integer or a slice (start:stop or start:stop:step) and you have used a tuple instead.
```
It would be better:
```
You seem to have forgotten a comma to separate [1,2,3] with [3,4,5]. The second list has been interpreted as the indexation of the object [1,2,3] by the index (3,4,5) which is not valid for [1,2,3] which is a list.
```

This message could also be applied to the following as it is the same case
```python
a=[1,2,3]
foo(a
    [4,5,6]
    )
```
```
You seem to have forgotten a comma to separate a with [3,4,5]. The second list has been interpreted as the indexation of the object a by the index (3,4,5) which is not valid for a which is a list.
```

**Comment by sdementen** [comment]
I am not using friendly-traceback. I saw it in some python newsletter/planet python and found it great for beginners.
When I read your blog post on the contest, I found in a fun way to contribute to your project.
I have just played 1h with it with the last exceptions I experiences in my daily pythoning.

**Comment by aroberge** [comment]
Right ... The problem I face with what you suggest as the explanation is created by my use of https://github.com/alexmojaki/executing to isolate the location (ast node) of the error. See it highlighted when both lists are on the same line:
![image](https://user-images.githubusercontent.com/629698/105400622-933b7b80-5bfb-11eb-8a9c-4aff3ce47fb2.png)

Since I focus on this code (which is what Python identifies as the error), I have no access to the larger context that indicates (to a human reader) that the two lists are actually intended to be function arguments.  Still, I could probably add something about possibly missing a comma between the two lists.

**Comment by sdementen** [comment]
Yes, the fact that it was use in a function call is not relevant for the analysis and the message (as well as too difficult to analyse/detect.
If it was a list of list were one comma between lists was missing should trigger the same message.

**Comment by sdementen** [comment]
Do you accept also pandas specific issues?

**Comment by sdementen** [comment]
And btw, I liked also your reeborg project to interest (my) kids to programming but haven't yet tried it.

**Comment by aroberge** [comment]
I'm potentially interested in Panda specific issues ... but they would be treated with very low priority as I want to focus on more basic exceptions first. Still, it would not hurt to collect them.

As for Reeborg's world: it's how I started with Python as a hobby in 2004, creating a desktop version (rur-ple) which eventually became Reeborg's world.

**Comment by sdementen** [comment]
a pandas wrong indexation with list comprehension
```python
df = df[col for col in df.columns]
```
gives
```
│ The opening square bracket [ on line 1 is not closed.                    │
│                                                                          │
│ 1: df = df[col for col in df.columns]                                    │
│           |                                                              │
└─────────────────────────────────────────────────────────────────
```
improved explanation: It seems you want to use a list comprehension to index an object. You are missing [] around your list comprehension. The current [] are understood as an indexation. Try: df = df[ [col for col in df.columns] ]

**Comment by gdementen** [comment]
> ```python
> def foo(a,b):
>     pass
> 
> # there is a missing trailing comma between the two lists
> foo([1,2,3]
>     [3,4,5])
> ```

Happens to me too from time to time (after I don't know how many years of Python). PS: Hello Sebastien 😉

**Comment by sdementen** [comment]
Hello Gaëtan ;-)

**Comment by aroberge** [comment]
Trailing comma by mistake fixed:
```

╭────────────────────────── Python exception ───────────────────────────╮
│ Traceback (most recent call last):                                    │
│   File "ignore.py", line 2, in <module>                               │
│     print(something.upper())                                          │
│ AttributeError: 'tuple' object has no attribute 'upper'               │
│                                                                       │
│ Did you write a comma by mistake?                                     │
│                                                                       │
│ An AttributeError occurs when the code contains something like        │
│ object.x and x is not a method or attribute (variable) belonging to   │
│ object.                                                               │
│                                                                       │
│ something is a tuple that contains a single item which does have      │
│ 'upper' as an attribute. Perhaps you added a trailing comma by        │
│ mistake at the end of the line where you defined something.           │
│                                                                       │
│ Exception raised on line 2 of file 'ignore.py'.                       │
│                                                                       │
│        1: something = "abc",                                          │
│     -->2: print(something.upper())                                    │
│                 ^^^^^^^^^^^^^^^                                       │
│                                                                       │
│     something: ('abc',)                                               │
╰───────────────────────────────────────────────────────────────────────╯

```

**Comment by aroberge** [comment]
TypeError caused by missing comma before a list has been "fixed".
![image](https://user-images.githubusercontent.com/629698/108204932-c984f180-70fa-11eb-8533-8e19d15165ec.png)
