### ISSUE TITLE
quoted function names

### ISSUE THREAD

**Issue by gdementen** [aroberge/friendly-traceback#156]
```python
>>> def "func"(a):

Traceback (most recent call last):
  File "<friendly-console:4>", line 1
    def "func"(a):
        ^
SyntaxError: invalid syntax
```
(also an example of code I have seen by one of my "students")

**Comment by aroberge** [comment]
Definitely something that I could and should identify.  In a few minutes, I will add this to issue #145 where I keep track of all valid entries.

**Comment by aroberge** [comment]
Fixed in repo
![image](https://user-images.githubusercontent.com/629698/105544057-f0edc780-5cd0-11eb-90d0-b58d6b4f3928.png)

Also included the following:

![image](https://user-images.githubusercontent.com/629698/105544091-fc40f300-5cd0-11eb-9c9e-20d05565e898.png)

**Comment by gdementen** [comment]
Nice! 

I wonder if there isn't a better explanation possible for beginners than "a Python identifier". In my opinion, in an ideal world, and if that is at all possible, the first  case should mention something like either 'a Python identifier may no contain quotes' or "The name of a function may not contain quotes". And the second case "may not start by a number". I know this would mean a lot of (probably too much) work because you'd have an explosion of possible error messages but still, I don't expect a beginner to know the rules for valid Python identifiers (or even what is an identifier) so I can't help but wonder if something better is possible.

**Comment by aroberge** [comment]
Here's what I'm thinking as a replacement for `The name of a function must be a Python identifier.".
```
The name of a function must be a valid Python identifier,
that is a name that begins with a letter or an underscore character, `_`,
and which contains only letters, digits or the underscore character.
```
I plan to keep the extra explanation using a string (as written), but not try to figure out other cases, such as using some forbidden unicode characters, etc.

**Comment by gdementen** [comment]
Very nice!

**Comment by aroberge** [comment]
Closing after having added test cases.
