### ISSUE TITLE
SyntaxError for misplaced `if/else` for ternary operator in comprehension

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#169]
```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = [i for i in range(9) if i%2 else 'divisible by 2']

Traceback (most recent call last):                                                                                                                                    
  File "<friendly-console:1>", line 1                                                                                                                                 
    x = [i for i in range(9) if i%2 else 'divisible by 2']                                                                                                            
                                    ^                                                                                                                                 
SyntaxError: invalid syntax
```

The intent was most likely `[i if i%2 else 'divisible by 2' for i in range(9)]`. This one is pretty popular on [StackOverflow](https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension).

Similarly a misplaced `if` inside a comprehension could occur:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> x = [i if i%2 for i in range(5)]

Traceback (most recent call last):                                                                                                                                    
  File "<friendly-console:1>", line 1                                                                                                                                 
    x = [i if i%2 for i in range(5)]                                                                                                                                  
                  ^                                                                                                                                                   
SyntaxError: invalid syntax
```

**Comment by aroberge** [comment]
On the one hand, this is an interesting case. However, when I wrote the contest "rules", for SyntaxErrors, I had specified code that contained only one mistake; I had in mind a single token mistake but didn't write this, and so I considered slightly more complex cases like missing two parentheses as valid.   These examples you gave contain one "logical" mistake in that a group of tokens is misplaced with respect to the other ones.  So, they are consistent with the rules as written ... but I have little hope to ever be able to identify them and give a proper explanation.

Still, I will consider them as a valid entry, especially with the reference to StackOverflow.

**Comment by Dominik1123** [comment]
No problem, it's not so much about the contest, I just want to help improve the application (cause I think it's pretty nice) :slightly_smiling_face: 

I don't know how the error analysis works under the hood but since the `SyntaxError` already points to the misplaced `else`, couldn't it check that this happened inside a list comprehension and then identify the error based on the pointed-to `else`?

**Comment by aroberge** [comment]
I will have to see if it is possible.
