### ISSUE TITLE
SyntaxError for illegal string prefix combination

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#173]
Formatted byte literals are [not allowed](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals), so the prefix combination `bf` raises a SyntaxError. A hint is given, but in that special case perhaps the intent of the programmer *was* to use it as a prefix:

```
$ python -m friendly_traceback

Friendly Console version 0.2.19. [Python version: 3.9.0]

>>> a = b'123'        
>>> bf'{a}'        

Traceback (most recent call last):                                                                                            
  File "<friendly-console:2>", line 1                                                                                         
    bf'{a}'                                                                                                                   
      ^                                                                                                                       
SyntaxError: invalid syntax                                                                                                   

Did you forget something between bf and '{a}'?
```

In that case, the hint could mention that `bf` is an illegal string prefix.

This seems to be popular also on [StackOverflow](https://stackoverflow.com/questions/45360480/is-there-a-formatted-byte-string-literal-in-python-3-6).

**Comment by aroberge** [comment]
Given the misleading information, this is definitely an invalid case.

**Comment by aroberge** [comment]
Sorry, I meant valid.
