### ISSUE TITLE
SyntaxError when attempting to use keyword 'arguments' inside subscript

### ISSUE THREAD

**Issue by Dominik1123** [aroberge/friendly-traceback#179]
```
$ echo "foo[x=1]" > test.py && python -m friendly_traceback test.py

╭────────────────────────────────────────────────────── Python exception ──────────────────────────────────────────────────────╮
│ Traceback (most recent call last):                                                                                           │
│   File "test.py", line 1                                                                                                     │
│     foo[x=1]                                                                                                                 │
│          ^                                                                                                                   │
│ SyntaxError: invalid syntax                                                                                                  │
│                                                                                                                              │
│ A SyntaxError occurs when Python cannot understand your code.                                                                │
│                                                                                                                              │
│ Python could not understand the code in the file 'test.py' beyond the location indicated by --> and ^.                       │
│                                                                                                                              │
│     -->1: foo[x=1]                                                                                                           │
│                ^                                                                                                             │
│                                                                                                                              │
│ The opening square bracket [ on line 1 is not closed.                                                                        │
│                                                                                                                              │
│ 1: foo[x=1]                                                                                                                  │
│       |                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

The hint doesn't seem correct in this case. There's a [draft PEP](https://www.python.org/dev/peps/pep-0637/) on this topic and a (somewhat unpopular) [question on SO](https://stackoverflow.com/questions/31916617/using-keyword-arguments-in-getitem-method-in-python/41999773).

**Comment by aroberge** [comment]
The incorrect hint has already been fixed ... but there is still no explanation given.

The problem I have is the following: is it the `=` sign that is incorrect (as flagged by Python) or is it the use of square brackets intead of parentheses.

**Comment by Dominik1123** [comment]
I would prefer to assume that this isn't a typo, but that the user actually wanted to use what they typed. Especially for this case, it's a reasonable construct and it might not be obvious to a beginner why `x=y` cannot be used inside subscripts, especially when they can define `__getitem__(self, index, *, foo):` to have additional parameters, potentially even keyword-only.

**Comment by aroberge** [comment]
Good point.

**Comment by aroberge** [comment]
@Dominik1123 You are the winner of the contest. Could you email me at andre.roberge@gmail.com so that I could make the arrangements for you to get your prize?

**Comment by Dominik1123** [comment]
@aroberge First of all, thank you for organizing this contest, it was fun to participate and I could learn something new along the way :slightly_smiling_face: I'm glad if the contributions help you to improve the friendly-traceback application. As for the prize, I would like to donate it to the [NumPy project](https://numpy.org/about/#donate), so if you could do that, I'd be grateful. Thanks.

**Comment by aroberge** [comment]
![image](https://user-images.githubusercontent.com/629698/105778706-46c9a600-5f43-11eb-98e2-278fbc65043e.png)

**Comment by aroberge** [comment]
Given
```python
foo[x=1]
```
the following would be valid syntax:
```python
foo[x:1]
foo[1]
foo(x=1)
```
Of these, the first one requires the fewer changes of tokens (replacing `=` by `:`). However, if the idea is to retrieve a single element, the second case is what is desired.  The situation is further complicated, if we have something like 
```python
foo[2, a=10]
```
as mentioned in the SO question referenced previously. In this case, the only "small" change that would yield valid syntax would be the replacement of square brackets by parenthesis.

Without the benefit of knowing the type of object `foo` refers to (which we cannot determine, as the code would not compile), any guess made would have a high likelihood of being wrong.  So, I consider this to be beyond the scope of what Friendly-traceback can do.
