### ISSUE TITLE
Investigate using Friendly-traceback with IDLE

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#183]
(Edited)

Starting with Python version 3.10.a5, IDLE's repl respects reassignments of `sys.excepthook` from user's code. In this issue, we keep track of progress in integrating Friendly-traceback with IDLE.

At present, `SyntaxErrors` for code entered in IDLE's shell cannot be "diverted" so that Friendly-traceback can process them.

The current version of Friendly-traceback uploaded to Pypi is 0.2.27. Unless otherwise noted, the screenshots below have been taken with that version. 

## The basics
There are different ways of using Friendly-traceback with IDLE. For all of them, one must use the following:
```python
from friendly_traceback.idle import *
```
This ensures that helper functions, such as `explain()`, `why()`, `what()`, etc., are available.

## Using IDLE's repl

To use Friendly-traceback within IDLE's repl, use the following:
```python
from friendly_traceback.idle import *
install()
```

**Warning**: if you do not include the `.idle`, Friendly-traceback will **not** be installed correctly in IDLE.

Here's an example:

![image](https://user-images.githubusercontent.com/629698/107527449-32b2b500-6b8f-11eb-96b1-1c67d6bd891c.png)

When we can narrow down the part of a statement causing an exception, we indicate it by highlighting it the same way that IDLE highlight the location of a syntax error.  However these marks are removed every time a syntax error occurs in IDLE's repl.

![image](https://user-images.githubusercontent.com/629698/107527716-773e5080-6b8f-11eb-863a-b2488ffbde24.png)

When Friendly-traceback is used this way, no additional information can be obtained for syntax errors. In fact, in the above, we don't even see what line caused the problem in the traceback.

If we are interested in getting help with syntax errors in a repl, we must use Friendly-traceback's own console:

```python
from friendly_traceback.idle import *
install()
```
Here's an example:

![image](https://user-images.githubusercontent.com/629698/107528073-d1d7ac80-6b8f-11eb-8411-78cac62a4c93.png)

## Running a module

Instead of running a module directly from IDLE, we use a second file, ideally located in the same directory as the module that we actually want to run.

Here's an example:

![image](https://user-images.githubusercontent.com/629698/107528398-2844eb00-6b90-11eb-9236-2e15b1e89511.png)
and the result:
![image](https://user-images.githubusercontent.com/629698/107528427-30048f80-6b90-11eb-91e0-7bf708c1ed97.png)

If we want to have help for syntax errors in the repl as we continue the session, we can use a keyword argument with `run()`:

![image](https://user-images.githubusercontent.com/629698/107528538-588c8980-6b90-11eb-8714-a87106374fb2.png)

This will start the Friendly console instead of IDLE's shell

![image](https://user-images.githubusercontent.com/629698/107528621-6a6e2c80-6b90-11eb-8d70-37b5da07a094.png)

## Other Python versions

Currently, when installing Friendly-traceback in IDLE, we determine if Python's version is known to support the integration of Friendly-traceback; if not, we fall back to using's Friendly-traceback's repl.

![image](https://user-images.githubusercontent.com/629698/107528243-ff245a80-6b8f-11eb-8518-bfc0516d3f7e.png)

**Comment by aroberge** [comment]
Recording first thoughts. To integrate Friendly-traceback into IDLE, in a similar way as I do for IPython, will actually be quite tricky. Just to recap: for IPython, there are two main methods that I monkeypatch (https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/ipython.py):
```
shell.InteractiveShell.showtraceback()
shell.InteractiveShell.showsyntaxerror()
```
Unfortunately, with IDLE, there would be 3 methods that would need to be replaced ... and it is not clear that this can be done for all three cases.

For runtime exceptions (i.e. excluding SyntaxError and similar), a "clean" traceback is obtained by IDLE using `idlelib.run.cleanup_traceback()` (https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/idlelib/run.py#L250); this is similar to what I do with `core.get_records()` (https://github.com/aroberge/friendly-traceback/blob/7d56152b95a5f82cb6f1be0e10baed0ef509c148/friendly_traceback/core.py#L94). 

For IDLE, individual lines of code are obtained using a remote call to `linecache()`. https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/idlelib/run.py#L277
Instead of using `linecache` from the standard library, a modified version, `extended_linecache_checkcache()` found in `idlelib.pyshell` is used (https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/idlelib/pyshell.py#L103).

When needed, I do something similar for Friendly-traceback, using `Cache.get_lines()` found in source_cache.py (https://github.com/aroberge/friendly-traceback/blob/7d56152b95a5f82cb6f1be0e10baed0ef509c148/friendly_traceback/source_cache.py#L50) 

In principle, by having a simple hook to get lines of code from IDLE's shell, it should be possible to use Friendly-traceback directly in IDLE's shell for runtime errors.  For example, doing a simple installation, we see IDLE's code itself being included in the traceback:

```
>>> from friendly_traceback import install
>>> install()
>>> 1/0

Traceback (most recent call last):
  File "PYTHON_LIB:\idlelib\run.py", line 559, in runcode
    exec(code, self.locals)
  File "<pyshell#2>", line 1, in <module>
    
ZeroDivisionError: division by zero

    A `ZeroDivisionError` occurs when you are attempting to divide
    a value by zero:
        `result = my_variable / 0.`
    It can also happen if you calculate the remainder of a division
    using the modulo operator `%`:
        `result = my_variable % 0`
    or if you try to raise 0 to a negative power.
    
    Execution stopped on line 559 of file PYTHON_LIB:\idlelib\run.py.
    
       557:             interruptable = True
       558:             try:
    -->559:                 exec(code, self.locals)
       560:             finally:

            code: <code object <module>>
            self.locals: {'__name__': '__main__', '__doc__': None, '__package__': None, ...}
                len(self.locals): 8
            self: <idlelib.run.Executive object>
            exec: <builtin function exec>
            locals: <builtin function locals>
        
    Exception raised on line 1 of file <pyshell#2>.
    
    -->1: 
>>> 
```
We can get a better result if we exclude the relevant file from IDLE.
```
>>> from friendly_traceback import exclude_file_from_traceback
>>> from idlelib import run
>>> exclude_file_from_traceback(run.__file__)
>>> 1/0

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    
ZeroDivisionError: division by zero

    A `ZeroDivisionError` occurs when you are attempting to divide
    a value by zero:
        `result = my_variable / 0.`
    It can also happen if you calculate the remainder of a division
    using the modulo operator `%`:
        `result = my_variable % 0`
    or if you try to raise 0 to a negative power.
    
    Exception raised on line 1 of file <pyshell#6>.
    
    -->1: 
>>> 
```
All that is missing to do a better error analysis are the actual lines of code that were saved as "files" with names starting with `<pyshell`.

= = = = = = = =

Unfortunately, for SyntaxError and similar, the situation is a lot more complicated.  IDLE distinguish between two different cases:
1. if SyntaxErrors are the result of code entered in the interpreter. In this case, `ModifiedInterpreter.showsyntaxerror` is used
(https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/idlelib/pyshell.py#L705).
2. if the errors are found in a file imported, it is the original InteractiveInterpreter.showsyntaxerror that is used (https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/idlelib/pyshell.py#L671)

By the time IDLE is running, I am guessing that it is impossible to monkeypatch these methods and substitute custom methods from Friendly-traceback, like we do for IPython, since the ModifiedInterpreter instance would already be running.

**Comment by terryjreedy** [comment]
In the standard terminal REPL, all entries are sent to Python to be compiled and executed.  Compile exceptions are handled by sys.excepthook, just like other exceptions.  In IDLE, code is compiled in the IDLE process and the resulting code object is sent to the user process for execution with exec().   ModifiedInterpreter.showsyntaxerror  is IDLE's compile-time excepthook.  To more completely imitate the REPLs execution of user code, showsyntaxerror should be replaceable, even the parent showsyntaxerror is not.  I will think about how we might enable this.  An IDLE extension might be a possibility.

ModifiedInterpreter.execfile is only used for code execution on startup, via command line options, before printing the initial >>> prompt, and before one could import friendlytraceback.  Of course, one might put the import in the startup code

**Comment by aroberge** [comment]
@terryjreedy New version (0.2.22) of Friendly-traceback uploaded to Pypi with partial support for IDLE's REPL.

Other than a relatively minor formatting issue (which I thought I had taken care of), runtime errors are correctly handled. SyntaxErrors in imported files are also handled correctly. However, SyntaxErrors for code entered in the REPL are still not handled by Friendly-traceback: I have been unable to bypass `ModifiedInterpreter.showsyntaxerror`.

Here are some screen captures. First, a runtime error (with an arrow showing the slight formatting problem where `^^^^` should be below `d[2]`.
![image](https://user-images.githubusercontent.com/629698/107157052-5344fa00-6958-11eb-8d03-afcf19b60304.png)

Next, a SyntaxError from an imported file.
![image](https://user-images.githubusercontent.com/629698/107157064-6657ca00-6958-11eb-88a5-cd640b832626.png)

Finally, a SyntaxError for code entered at the REPL.
![image](https://user-images.githubusercontent.com/629698/107157073-74a5e600-6958-11eb-8841-16181c2a0590.png)

**Comment by aroberge** [comment]
Work in progress - Added color to friendly tracebackin IDLE shell, hoping that it might increase readability. Version 0.2.24 uploaded to Pypi.
![image](https://user-images.githubusercontent.com/629698/107304771-1fe99480-6a58-11eb-9c3e-4d7b61ca5d92.png)

**Comment by aroberge** [comment]
Closing this issue as nothing more can be done for now.
