### ISSUE TITLE
std install don't package the locales (gettext)

### ISSUE THREAD

**Issue by SylAxel** [aroberge/friendly-traceback#21]
Lang option work only with develop mode, I had this into setup.py to package data:

```python
package_data={"gettext": ["friendly_traceback/locales/*"]},
include_package_data=True,
```

**Comment by aroberge** [comment]
Thanks for the report. As soon as I have a bit of time to work on this, I will fix it.

**Comment by aroberge** [comment]
@SylAxel I tried three times to fix it, but when I try to install it on another computer, the language data is not included.  Could you possibly have a look at the latest version of setup.py and see if I missed something?

**Comment by aroberge** [comment]
@SylAxel Got it!  I needed to create a manifest.in file with the path information as to where to find the translation files.

Once again, thank you for pointing out this problem and some essential parts for its resolution. I will likely leave this issue open until I hear back from you.

**Comment by SylAxel** [comment]
Perfect, the fix works well!
