### ISSUE TITLE
Wrong URL in blog post

### ISSUE THREAD

**Issue by encukou** [aroberge/friendly-traceback#22]
Hello @aroberge!
The [blog post](https://aroberge.blogspot.com/2019/06/abolishing-syntaxerror-invalid-syntax.html?m=1) linked from a recent PSF update links to a missing page: in “Glance through of exceptions on [this page](https://aroberge.github.io/friendly-traceback-docs/docs/html/tracebacks_en.html)”, the URL is missing a version like [`_3.8`](https://aroberge.github.io/friendly-traceback-docs/docs/html/syntax_tracebacks_en_3.8.html). Same for the following link, "included here".

(I hope this is an OK-ish place to report this. The blog seems to have a comment mechanism but my ad blocker doesn't trust it.)

**Comment by aroberge** [comment]
Thanks, I will have to fix this.

**Comment by aroberge** [comment]
Fixed two wrong urls on blog post.
