### ISSUE TITLE
Add new public method to simply compile/check the code

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#26]
Like the title said. This might make it easier to use as a plugin in various editors, when one needs more explanation about a syntax error possibly flagged by the editor.

**Comment by ntoll** [comment]
:+1: :clap:

**Comment by aroberge** [comment]
Need to
 - [ ] Add docstring
 - [ ] Add translation
 - [ ] Provide an explanation for `FileNotFoundError` ... which I do not do yet!
 - [ ] Add a new level (8?) so that the location of the error when a `FileNotFoundError` exception is raised does not show (it is Friendly-traceback's own code which cannot be excluded here)
- [ ] review documentation; need to include information about `check_syntax` as well as review the information about the various ways to use friendly-traceback.

**Comment by aroberge** [comment]
First complete implementation done - with basic documentation added. To do:

- [ ] add unit tests.

**Comment by aroberge** [comment]
@ntoll This is ready to be tested. There's a second function (`run_code`) which first calls `check_syntax` and, if no syntax error is found, will execute the code, and give a friendly traceback if any exception is raised. Thus it will give informative message for both syntax errors and run time errors.   I believe that something like this is what should be used in editors such as Mu: have the preferred Python interepreter run the user code but, if an exception is raised, give the option for the user to process that code using this friendly-traceback function.  

Using this function only modifies `sys.excepthook` during the function call: it reverts back to the original Python version (`sys.__excepthook__`) at the end. 

(I just realized that I should first make a copy of whatever is used for `sys.excepthook`, execute the code in the function, and restore `sys.excepthook` to what it was before rather than assuming that the Python default was used.)

The code for the function is found at https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/core.py#L168  This is below the code for `check_syntax`.

A unit test is found in https://github.com/aroberge/friendly-traceback/blob/master/tests/test_run_code.py

I don't really have an idea as to how it should be incorporated into Mu ... but I think it should. :-)

Right now, it is not part of a release on pypi.  I'll try to make a new release tomorrow  (Sunday) afte making the change for properly restoring `sys.excepthook`.

**Comment by ntoll** [comment]
@aroberge you can track what Mu is doing in this respect via the ticket I just created which references this one. Thank you for all your hard work so far on friendly-traceback. It's really appreciated and I'm looking forward to testing it out with out users (I have both beginner adults and kids with whom I can try it out and gather feedback as well as a bunch of teachers for whom this would be very interesting). In any case, I'll share any feedback I get.
