### ISSUE TITLE
`public_api.__all__` misses several entries

### ISSUE THREAD

**Issue by aivarannamaa** [aroberge/friendly-traceback#37]
I'm experimenting with public API methods (eg. `explain`). My IDE (PyDev) doesn't see them attached to `friendly_traceback` module. Probably it's because they are missing from `friendly_traceback.public_api.__all__` list.

**Comment by aroberge** [comment]
They are included:

```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32                                          
Type "help", "copyright", "credits" or "license" for more information.                                                                
>>> from friendly_traceback import public_api                                                                                         
>>> public_api.__all__                                                                                                                
['cache', 'check_syntax', 'exec_code', 'highlight_source', 'exclude_file_from_traceback', 'is_excluded_file', 'include_file_in_traceba
ck', '__version__', 'explain', 'install', 'uninstall', 'is_installed', 'get_output', 'set_formatter', 'set_lang', 'get_lang', 'set_lev
el', 'get_level', 'set_stream', 'get_stream', 'clear_traceback', 'copy_traceback_info', 'show_traceback_info_again']                  
```                                                      

I too have looked at seeing if I could easily use Friendly-traceback with Thonny, but have not been able to - at least not yet.

**Comment by aivarannamaa** [comment]
Now I noticed the `make_public` trick, but as PyDev doesn't execute the module, this is not visible for the code completer. BTW, jedi completer used in Thonny doesn't see through it either. I suspect MyPy and other static analysis tools will also stumble on it.

I was able to integrate friendly_traceback into Thonny. I'll send you the details when I'm done with the configuration part. I was talking about PyDev, because I'm developing Thonny in it.

**Comment by aroberge** [comment]
I didn't realize that using a decorator would cause problems. I just saw this as an easy way to avoid forgetting to include some functions.  If needed, I can stop using this and explicitly add the name in `__all__`: it would be a minor edit for me to do.

**Comment by aroberge** [comment]
Also, in case you install from pypi.org, note that `run_program` has been removed from version 0.0.26 (latest version on pypi) but is still present in the repository as I didn't commit the corresponding changes; https://github.com/aroberge/friendly-traceback/blob/master/friendly_traceback/public_api.py#L250

If it is needed for Thonny, I can put it back in.

**Comment by aivarannamaa** [comment]
I used following methods

* `set_level`
* `set_lang`
* `exclude_file_from_traceback`
* `explain(redirect="capture")`
* `get_output`

The result is in Thonny's master and the instructions are here: https://github.com/thonny/thonny/issues/1028

If you are happy with this, then I'll try to make a release before holidays.

**Comment by aroberge** [comment]
This works beautifully!  I had been thinking of trying to write a Thonny
plugin, but it is clearly not needed.

I will add a page in the documentation for Friendly-traceback to show how
it works with Thonny, with screenshots.

I was thinking of modifying some of the descriptions I had to include parts
of some of the suggestions mentioned by the Assistant - I may still do this
at some point.

When I update the documentation, I will let you know so that you can let me
know if I should change anything.

Thank you!

**Comment by aivarannamaa** [comment]
Great!
