### ISSUE TITLE
SyntaxError: missing double colon on for loop

### ISSUE THREAD

**Issue by stdedos** [aroberge/friendly-traceback#42]
```
File "./bbq.py", line 160
    for config_file in config_files
                                  ^
 SyntaxError: invalid syntax
```

from: https://mail.python.org/archives/list/python-ideas@python.org/thread/RMAZTJ3RO5L5RNHGTAPVE4UL2GXIWTSO/#ILJNAN4E5VROSODWO2UWJDHP5DCVM56G

**Comment by aroberge** [comment]
I saw that. This case is already taken care of by Friendly-traceback. For example:

```
$ python -m friendly_traceback
Friendly Console version 0.0.28a. [Python version: 3.7.3]

>>> for a in b

    Python exception:
        SyntaxError: invalid syntax

    A SyntaxError occurs when Python cannot understand your code.

    Python could not understand the code in the file
    '<friendly-console:1>'
    beyond the location indicated below by --> and ^.

    -->1: for a in b
                    ^

    I don't have enough information from Python:
        I make an effort below to guess what caused the problem
        but I might guess incorrectly.

        You wrote a 'for' loop but
        forgot to add a colon ':' at the end


>>>
```

**Comment by aroberge** [comment]
I should have written: I saw that, reading Python-ideas on Google groups, but I am not subscribed to it so that I could not simply reply.

**Comment by stdedos** [comment]
I was planning to test tomorrow, as I am right now on Windows! 😕 

Let's see if I can come up with a quick way of interfacing parsing a file via `friendly_traceback`, or "parsing the python output itself".

However, if such functionality exists, IMHO it should be directly on project's README.md

**Comment by aroberge** [comment]
You can do that and even more; there is simply too much to mention in the readme. The readme file points to the documentation: https://aroberge.github.io/friendly-traceback-docs/docs/html/

**Comment by aroberge** [comment]
BTW, I do all my development on Windows ... so you don't have to wait to try it. ;-)

**Comment by stdedos** [comment]
I know (I have just downloaded Mu btw).
Regardless, I feel I could die by using cmd/powershell 😄

**Comment by stdedos** [comment]
Oh, btw - I am not sure why have you kept the issue open, since you have already done that.

AFAIC you may close it; I'll send an e-mail on the list so that it remains upstream myself

**Comment by aroberge** [comment]
I keep it open for discussion while it is still discussed on Python-ideas.
