### ISSUE TITLE
Debian package ?

### ISSUE THREAD

**Issue by stuaxo** [aroberge/friendly-traceback#44]
Is there any chance of a debian package, e.g. `python3-friendly-traceback` ?

This would make it easier to use friendly-traceback in python/gtk based projects there.

**Comment by aroberge** [comment]
I have no idea about what's involved in creating a debian package.  friendly-traceback is a pure python package with no dependencies other than what is found in Python's standard library.

I will leave this issue open in the hope that someone else can provide an answer.

**Comment by stuaxo** [comment]
Cheers, and feel free to close if it hangs around too long unanswered :)

(I've been procrastinating on learning this very thing for a while now)
