### ISSUE TITLE
Newcomers copy/pasting from repl

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#52]
I see a lot of:
```pytb
Traceback (most recent call last):
  File "solution.py", line 1
    >>>print("Hello World!")
     ^
SyntaxError: invalid syntax
```

from newcomers code, is this the kind of stuff `friendly-traceback` also want to spot and write a nice message like: "Looks like you copy-pasted from an interactive interpreter, you also took the `>>> ` prompt, which is only presentation in the interpreter, not actual Python code".

If this is also the kind of stuff friendly-traceback want to catch, I'll gladly implement it myself.

**Comment by aroberge** [comment]
Please feel free to go ahead: this is definitely a good addition which I
would never have thought of.  If you don't do it, I definitely will add it
to my todo list.

Tangentially related: over the years, I have found that many good additions
to my project came from such suggestions. Unsurprisingly, the more
visibility a given project had, the more suggestions I got.  With this in
mind, would you mind including a note on Hackinscience.org indicating that
it uses Friendly-traceback, and that users should feel welcome to open
issues on Friendly-traceback if they found an explanation that was either
misleading or not really helpful?

**Comment by JulienPalard** [comment]
> Please feel free to go ahead

You're definitely faster than me :)

> Tangentially related: over the years, I have found that many good additions to my project came from such suggestions. Unsurprisingly, the more visibility a given project had, the more suggestions I got. With this in mind, would you mind including a note on Hackinscience.org indicating that it uses Friendly-traceback, and that users should feel welcome to open issues on Friendly-traceback if they found an explanation that was either misleading or not really helpful?

This is already the case, but maybe not enough:

![Screenshot_2020-07-27 HackInScience - Hello World](https://user-images.githubusercontent.com/239510/88540257-e3ea6700-d012-11ea-9a7f-77ac966229c7.png)

First it could be displayed as a clickable link instead. If you have any other idea on where I could place it, don't hesitate, I'll gladly add it.

**Comment by aroberge** [comment]
Well ... I do have a sense of pride in making sure that I take care of important issues raised by users!

I forgot about the info automatically added.  Still, and assuming you and your teammates are ok with it, perhaps a single sentence on https://www.hackinscience.org/about/ might be "useful". 

And now, I have one more SyntaxError case to add!  (dot preceding a paren)

**Comment by JulienPalard** [comment]
> perhaps a single sentence on https://www.hackinscience.org/about/ might be "useful".

What about the freshly added "Friendly Tracebacks in corrections" in https://www.hackinscience.org/about/? I took care to avoid people reporting issues from hackinscience (bad corrections on exercices) to your repo, hope it won't happen.

Don't hesitate to amend (just ask, or [PR](https://framagit.org/hackinscience/hkis-website/-/blob/master/website/templates/hkis/about.html#L34) it).

> And now, I have one more SyntaxError case to add! (dot preceding a paren)

haha :] had to query the db to find it. It's probably a good idea for me to run this query from time to time if you want.

**Comment by aroberge** [comment]
On Mon, Jul 27, 2020 at 9:38 AM Julien Palard <notifications@github.com>
wrote:

> perhaps a single sentence on https://www.hackinscience.org/about/ might
> be "useful".
>
> What about the freshly added "Friendly Tracebacks in corrections" in
> https://www.hackinscience.org/about/? I took care to avoid people
> reporting issues from hackinscience (bad corrections on exercices) to your
> repo, hope it won't happen.
>

That's more than I expected; thanks!

> Don't hesitate to amend (just ask, or PR
> <https://framagit.org/hackinscience/hkis-website/-/blob/master/website/templates/hkis/about.html#L34>
> it).
>
> And now, I have one more SyntaxError case to add! (dot preceding a paren)
>
> haha :] had to query the db to find it. It's probably a good idea for me
> to run this query from time to time if you want.
>
It's up to you. It might be useful ... and hopefully not overwhelming.

**Comment by JulienPalard** [comment]
It already helped someone:

![Screenshot_2020-07-28 HackInScience - Hello World (as seen by floofers)](https://user-images.githubusercontent.com/239510/88674850-993c1e00-d0ea-11ea-8b99-42bc8a8ec051.png)

**Comment by aroberge** [comment]
:-)

**Comment by aroberge** [comment]
Note that I changed today the heading
```
I don't have enough information from Python
```
to
```
Python's error message (invalid syntax) cannot be used to identify the problem:
```
I feel that this reinforces the idea to look at the message given by Python in order to understand the cause of an error.
