### ISSUE TITLE
Internal error not being an internal error?

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#58]
Just seen:

```python
if end == begin:  # The problem is in our own code!
    # Write in two places to make sure it is noticed!
    write_err("Internal problem with Friendly-traceback!\n")
    print("Internal problem with Friendly-traceback")
    return records
```

hitting me on hackinscience.org (again), but it does *not* look like a problem to me. It probably would be a problem if the cleaning resulted in 0 entries, but having one entry is OK to me (if I understand the check correctly).

I use friendly-traceback like this: https://github.com/JulienPalard/correction-helper/blob/master/correction_helper.py#L32

I have a `exclude_file_from_traceback(__file__)` in correction_helper.py AND in `check.py` (which is the file that uses correction_helper and import student code to test it).

So sometimes stacktraces are limited to the student code file (`solution.py`), which is OK, like:
```pytb
Traceback (most recent call last):
  File "solution.py", line 6
    ..
    ^
SyntaxError: invalid syntax
```

(the `..` is just me writing this to raise a SyntaxError to demo the issue)

**Comment by aroberge** [comment]
On Mon, Jul 27, 2020 at 2:37 PM Julien Palard <notifications@github.com>
wrote:

> Just seen:
>
> if end == begin:  # The problem is in our own code!
>     # Write in two places to make sure it is noticed!
>     write_err("Internal problem with Friendly-traceback!\n")
>     print("Internal problem with Friendly-traceback")
>     return records
>
> hitting me on hackinscience.org (again), but it does *not* look like a
> problem to me. It probably would be a problem if the cleaning resulted in 0
> entries, but having one entry is OK to me (if I understand the check
> correctly).
>

I believe that you are correct!

I'm going to remove the test.

Do you need me to do a new release to be able to use the changed version?



> I use friendly-traceback like this:
> https://github.com/JulienPalard/correction-helper/blob/master/correction_helper.py#L32
>
> I have a exclude_file_from_traceback(__file__) in correction_helper.py
> AND in check.py (which is the file that uses correction_helper and import
> student code to test it).
>
> So sometimes stacktraces are limited to the student code file (solution.py),
> which is OK, like:
>
> Traceback (most recent call last):
>   File "solution.py", line 6
>     ..
>     ^SyntaxError: invalid syntax
>
> (the .. is just me writing this to raise a SyntaxError to demo the issue)
>
Yes, you are quite correct about this.

**Comment by aroberge** [comment]
I should have run the tests before the last commit: a test of hte friendly-console is now failing ...

**Comment by JulienPalard** [comment]
Took the time to dig a bit more and I may have found a related issue, look the following special case: a single record is in the traceback, in this case the block:

```
for begin, record in enumerate(records):
    frame, filename, linenumber, _func, lines, index = record
    if is_excluded_file(filename):
        continue
    else:
        break
```

can't eliminate it: whatever `is_excluded_file` is `True` or `False,` the `for` loop ends, begin stays at 0, same for the following block (removing from the end): the record is kept.

reproducer:

```
import friendly_traceback

friendly_traceback.install()
friendly_traceback.exclude_file_from_traceback(__file__)
friendly_traceback.set_level(9)


import tests.syntax.raise_syntax_error1
```

it prints:
```
Traceback (most recent call last):
  File "repro.py", line 8, in <module>
    import tests.syntax.raise_syntax_error1
  File "/home/mdk/clones/friendly-traceback/tests/syntax/raise_syntax_error1.py", line 3
    def = 2
        ^
SyntaxError: invalid syntax
```

But it should have eliminated "repro.py" from the Traceback (I excluded it right before).

Time for a PR.
