### ISSUE TITLE
Dead code spotted

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#59]
In core.py around line 376:

```python
 if not records:
     if issubclass(etype, FileNotFoundError):
         set_cause(info, friendly, etype, value)
     return info

     info["cause"] = _(
         "I suspect that you are using a regular\n"
         "Python console after importing Friendly-traceback.\n"
         "Unfortunately, no further processing can be done.\n"
     )
     return info
```

the `return info` in the middle hides the following lines.

**Comment by aroberge** [comment]
On Mon, Jul 27, 2020 at 6:04 PM Julien Palard <notifications@github.com>
wrote:

> In core.py around line 376:
>
>  if not records:
>      if issubclass(etype, FileNotFoundError):
>          set_cause(info, friendly, etype, value)
>      return info
>
>
Good catch. It appears to have been introduced in the following commit
https://github.com/aroberge/friendly-traceback/commit/f68b0b969a28373f7cc883bfa432be2f057441f4
and
I suspect I simply forgot to indent the `return info`. However, I will need
to explore a bit more to confirm.
