### ISSUE TITLE
[idea] Propose near matches on attribute error.

### ISSUE THREAD

**Issue by JulienPalard** [aroberge/friendly-traceback#62]
Spotted this one:

```
## Python exception

    :::pytb
    Traceback (most recent call last):
      File "solution.py", line 3, in <module>
        print(string.ascii_lowecase[0,1])
    AttributeError: module 'string' has no attribute 'ascii_lowecase'

An attribute error occurs when the code contains something like
    object.x
and 'x' is not a method or attribute (variable) belonging to 'object'


### Likely cause based on the information given by Python

In your program, the object is 'string' and the attribute is 'ascii_lowecase'.


### Execution stopped on line 3 of file 'solution.py'.

    :::text
           1: import string
           2: 
        -->3: print(string.ascii_lowecase[0,1])


#### Variables

    :::text
        string: <module 'string' from '/usr/lib/python3.6/str...>
```

It would be great if we give:

    You probably misstyped 'ascii_lowercase' (you typed 'ascii_lowecase').

We could use this message when the [edit distance](https://en.wikipedia.org/wiki/Edit_distance) is 1, for example.

**Comment by aroberge** [comment]
On Tue, Jul 28, 2020 at 8:57 AM Julien Palard <notifications@github.com>
wrote:

> Spotted this one:
>
> ## Python exception
>
>     :::pytb
>     Traceback (most recent call last):
>       File "solution.py", line 3, in <module>
>         print(string.ascii_lowecase[0,1])
>     AttributeError: module 'string' has no attribute 'ascii_lowecase'
>
> An attribute error occurs when the code contains something like
>     object.x
> and 'x' is not a method or attribute (variable) belonging to 'object'
>
>
> ### Likely cause based on the information given by Python
>
> In your program, the object is 'string' and the attribute is 'ascii_lowecase'.
>
>
> ### Execution stopped on line 3 of file 'solution.py'.
>
>     :::text
>            1: import string
>            2:
>         -->3: print(string.ascii_lowecase[0,1])
>
>
> #### Variables
>
>     :::text
>         string: <module 'string' from '/usr/lib/python3.6/str...>
>
> It would be great if we give:
>
> You probably misstyped 'ascii_lowercase' (you typed 'ascii_lowecase').
>
>
Thonny does something similar, and also includes misspelled keywords
https://github.com/thonny/thonny/blob/c61b5a84b5ef1f8b35aafe66f10d95d205d490e8/thonny/plugins/stdlib_error_helpers.py#L267

As a first step, I agree that focusing on the case of a potentially
misspelled method or attribute would be useful.

**Comment by aroberge** [comment]
This has been implemented and ready to check.

There are two possible cases, depending if only one or many possible words can match.

See the result of the test cases starting at https://aroberge.github.io/friendly-traceback-docs/docs/html/tracebacks_en_3.8.html#attributeerror-typo-in-module-attribute

Version française: https://aroberge.github.io/friendly-traceback-docs/docs/html/tracebacks_fr.html#attributeerror-typo-in-module-attribute

**Comment by JulienPalard** [comment]
Looks good to me.
