### ISSUE TITLE
Breaking change: separating level (amount of information in traceback) and formatter

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#66]
# Possibly Breaking change - open for discussion

**This was revised**

## Current situation

Currently, setting an option named `--level` determines both the amount of information provided **and** sets up a formatting method. Furthermore, the "level" is an integer which can be positive or negative: the sign indicates if it is a true Python traceback or a simulated one that is shown to the user (not done by default, with `level==1`.

Using the recently introduced `--formatter` command line option, it is possible to set up separate formatters but they are then decoupled from any specified "level" and must handle everything on their own.

## Desired changes

Ideally, we should have the following that could be easily set by separate methods:
* the amount of information to be processed and shown; currently done via `set_level()`. A better name than `level` might be `verbosity`.
* what the format of the output be:
  * pre-formatted string, as is currently the case by default: done
  * formatted with markdown, as is currently available in a separate formatter: done, two different ways
  * formatted with colours on a console, as already mentioned in a recent issue: done

## Affected users

Since `set_level()` is currently used by Thonny, any change to be made should be temporarily backwards compatible with no visible change for Thonny users - even though friendly-traceback is still in "alpha" mode.

~HackInScience currently uses a custom formatter. Such an option should definitely remain. As is the case right now, If a custom formatter is used, it receives all the information recorded by friendly-traceback and put into a dict (`info`) is passed to the custom formatter; thus the verbosity/level setting is ignored. I would prefer if any option that uses third-party code has a name that begin with `--custom`.  Thus, the current `--formatter` option would become `--custom-formatter`. Perhas an even better, more future-proof alternative, is to simply have a single command line option, `--custom dotted_path.module` which results in importing a module that takes care of defining its own initialization including setting a custom formatter if desired.~

`--formatter` has been retained (as synonym of the new `--format`) and has been enhanced.

The only breaking change for HackInScience is that the full traceback is now a string instead of a list.

Other than Thonny and HackInScience, I am not aware of any other project (other than my own) that might be affected by such changes.

### Before introducing Version 0.1.x

As far as I know, only HackInScience currently uses the newly introduced `--formatter` option, whose code was provided by @JulienPalard. 

- [x] Add `set_verbosity()` to the public API as equivalent to `set_level()`
- ~[ ] Add **Changes to API** section to documentation.~
- [x] Add information about `set_verbosity()` in documentation.
- [x] Coordinate with Thonny to have it use `set_verbosity()` instead of `set_level()`. See https://github.com/thonny/thonny/blob/a464184d84d13f1b7b9cecb589883d5ee4a0f374/thonny/backend.py#L1372 **Revised:** Keep `set_level()` around as deprecated, but undocumented function.
    
  - [x] Communicate the information to Thonny users via the Google group discussion list.

### Version 0.1.x

Introduce Version 0.1.x

Enable new command line options and methods, while keeping all current options working as-is
- [ ] `--verbosity` as a positive integer or zero (currently equivalent to a positive `--level` option)
  - [x] Add corresponding `set_verbosity()` function to the API
  - [x] update documentation
  - [x] **Revised**: do not show `--level` option anymore but use it as a hidden synonym for `--verbosity`.
  - ~[ ] Print warning about deprecation when the function `set_level()` is used. **Does this needs to be postponed to accommodate Thonny users that would have installed an older version of Thonny with a new version of Friendly-traceback?**~
- [ ] ~`--true-tb`  (currently equivalent to a having a negative level option)~ Remove support for negative levels; simply use level 0 if Python traceback are desired.
  - ~[ ] Add corresponding `use_true_tb(True/False)` function to the API~
  - [ ] update documentation
- [x] Add a new command line option specifying the forma (pre-formatted string, markdown, etc.); this has been done with `--format` which is a synonym of the revised `--formatter`
  - [ ] update documentation
- ~[ ] Print a warning whenever a deprecated function (such as `set_level()`) is invoked.~ **Revised**: keep as undocumented function.

**Comment by aroberge** [comment]
For Thonny itself, perhaps using something like:
```python
try:
    friendly_traceback.set_verbosity(level)
except AttributeError:
    friendly_traceback.set_level(level)
```
might be the most user-friendly possibility.

**Comment by aivarannamaa** [comment]
Sorry for late reply! I'm happy to use `set_verbosity` in the next release, but it will take some time. Therefore I support the idea that the old method won't generate warnings yet.

**Comment by aroberge** [comment]
@aivarannamaa Thank you for the follow-up. I will keep `set_level()` available but hidden for longer than mentioned here.

For information: I am rewriting the documentation, and plan to mention Thonny as the first (and only) editor that is designed to support Friendly-traceback "out of the box", in addition to providing its own helpful advice through its assistant.
